### ISSUE TITLE
Error when including categorical variables

### ISSUE THREAD

**Issue by jnephin** [mrmaxent/maxnet#14]
Hi, I've come across an error ` Error in ifelse(x == category, 1, 0) : object 'Trap' not found ` when running the maxnet() function when one of the the predictor variables is a factor with character levels (in this example a 3 level factor: 'Dive', 'Trap' and 'Trawl'). I determined the source of the error (line 31, `rr <- predict(model, data[p == 0, , drop = FALSE], type = "exponent", clamp = F)`).  Looking into predict.maxnet() I see that the issue arises when model.matrix() is called because that calls categoricalval() in the formula. categoricalval() throws the error because there are no quotes around the factor levels and thus it looks for the Trap object and cannot find it.

**Comment by jamiemkass** [comment]
You could probably get it to work if you convert to a numerical factor, but you may have already tried this.
