### ISSUE TITLE
Possible typo in thresholds?

### ISSUE THREAD

**Issue by mkborregaard** [mrmaxent/maxnet#15]
I was reading the code for thresholds, and wondered whether this line

https://github.com/mrmaxent/maxnet/blob/master/R/thresholds.R#L7

should not contain `2:(nknots+1)` instead? The current code looks strange.

**Comment by mrmaxent** [comment]
I believe you're correct.  Fixing it now.

**Comment by mrmaxent** [comment]
Added parenthesis to fix the issue.
