### ISSUE TITLE
`predict.maxnet` shorter than 'newdata' when there are NAs

### ISSUE THREAD

**Issue by AMBarbosa** [mrmaxent/maxnet#17]
When predicting with a maxnet model over a dataframe with NA in a variable, the result is shorter than the dataframe and does not allow adding the prediction as a new column, or matching predictions to observations:
```
library(maxnet)
data(bradypus)
nrow(bradypus)  # 1116

mod <- maxnet(bradypus[ , "presence"], bradypus[ , -1])

pred <- predict(mod, newdata = bradypus)
length(pred)  # 1116 - same as nrow(bradypus)

# simulate an NA in one of the predictor variables in 'newdata':
bradypus[2, 2] <- NA

pred <- predict(mod, newdata = bradypus)

length(pred)  # 1115 - one less than nrow(bradypus) 

bradypus$pred <- predict(mod, newdata = bradypus)
# Error in `$<-.data.frame`(`*tmp*`, pred, value = c(0.119783762630692,  : 
# replacement has 1115 rows, data has 1116
```
If this is desired behaviour, it would be nice to at least have a `na.rm` argument in `predict.maxnet`, so that NAs could be kept and the predicted values would match the positions in 'newdata'.
Thank you!

**Comment by btupper** [comment]
Perhaps you can use a wrapper around maxnet::predict() to handle those cases when your data is incomplete.  Something like the following?

```
library(maxnet)

#' A wrapper around maxent::predict() that allows the user to account rows in 
#' the input that have one or more missing values.
#' 
#' @param object an object of class "maxnet", i.e., a fitted model.
#' @param newdata values of predictor variables to predict to, possibly
#'   matrix, data.frame, \code{SpatRaster} or \code{stars} object
#' @param na.rm logical, if TRUE (default) incomplete records in newdata are dropped.
#' @param ... other arguments for maxnet::predict()  
#' If FALSE then rows with incomplete rows are assigned NA_real_ prediction values. 
predict2 <- function(object, newdata, na.rm = TRUE, ...){
  if (!na.rm){
    ix <- complete.cases(newdata)
    newdata <- newdata[ix, , drop = FALSE]
  }
  
  pred <- predict(object, newdata, ...)
  
  if (!na.rm){
    p <- rep(NA_real_, length(ix))
    p[ix] <- as.vector(pred)
    pred <- p
  }
  return(pred)  
}



data(bradypus)

mod <- maxnet(bradypus[ , "presence"], bradypus[ , -1])

# simulate an NA in one of the predictor variables in 'newdata':
bradypus[2, 2] <- NA

cat("length with missing removed = ", length(predict2(mod, newdata = bradypus, na.rm = TRUE)), "\n")
# length with missing removed =  1115 
cat("length with missing retained = ", length(predict2(mod, newdata = bradypus, na.rm = FALSE)), "\n")
# length with missing retained =  1116

```

**Comment by AMBarbosa** [comment]
I can, but especially when using maxnet for teaching, these wrappers / additional functions confuse students a lot. They often make us spend precious time explaining code nuances, rather than focusing on the models, which are the actual subject. So, ideally this would be included in the package function ;)

**Comment by btupper** [comment]
I know what you mean!

I have submitted a [pull request](https://github.com/mrmaxent/maxnet/pull/22) which adds predictions onto SpatRasters or stars objects that does just that kind of checking.  I wasn't clever enough at the time to think about matrices and data.frames, too.  I'm happy to add it as another pull request assuming the first gets approved.

**Comment by btupper** [comment]
I added some optional handling of missing data to the pull request.   Note the new argument `incompletes` to the `predict.maxnet` function; this argument only has meaning if `newdata` is a data frame or matrix. The argument can have the value "ignore" (default value) which will silently drop incomplete cases or it can have the value "fill" in which case the function will fill missing predictions with `NA` rather than silently dropping them.

``` r
library(maxnet)
data(bradypus)
nrow(bradypus)  # 1116
#> [1] 1116

mod <- maxnet(bradypus[ , "presence"], bradypus[ , -1])

pred <- predict(mod, newdata = bradypus)
length(pred)  # 1116 - same as nrow(bradypus)
#> [1] 1116

# simulate an NA in one of the predictor variables in 'newdata':
bradypus[2, 2] <- NA

pred_ignore <- predict(mod, newdata = bradypus, incompletes = "ignore")
cat("pred without fill has", length(pred_ignore), "elements\n")  # 1115
#> pred without fill has 1115 elements

pred_fill <- predict(mod, newdata = bradypus, incompletes = "fill")
cat("pred with fill has", length(pred_fill), "elements\n")  # 1116
#> pred with fill has 1116 elements
```

<sup>Created on 2022-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by AMBarbosa** [comment]
That's awesome, thanks! Let's hope the pull request is approved soon! Cheers

**Comment by mrmaxent** [comment]
NA values in the input to predict.maxnet are now passed through to the output, so the output has the same number of rows.

**Comment by AMBarbosa** [comment]
@mrmaxent Is there a plan to submit the latest `maxnet` version (with this issue fixed) to CRAN? Cheers
