### ISSUE TITLE
Differences between maxent and maxnet

### ISSUE THREAD

**Issue by rpatin** [mrmaxent/maxnet#21]
Hello @mrmaxent,
Sorry I did not find a discussion tab so I opened it as an issue.
We use both `maxent` and `maxnet` within the `biomod2` package (https://github.com/biomodhub/biomod2), although the support for `maxent` is more tedious as we need to execute an external java software with specific constraint.
So we were wondering about the differences between both implementation and whether we would lose functionalities by dropping support for `maxent` and keeping only the `maxnet` R implementation. Do you have any advice on that ?
In any case, thank you for your work (and the quick integration of the PR).
Best,
Rémi

**Comment by btupper** [comment]
Hi,

I'm just learning how to use maxnet, and I'm not that knowledgeable about modeling even though I have coded with `dismo::maxent()` a lot.  Right out of the box there are a couple of things that differ from a coding perspective.  I'm hoping that by chiming in I can get answers, too.

+ `file-based storage` `maxent` writes files to a path of your choosing which makes subsequent restoration do-able (but not necessarily trivial).  `maxnet` does not, but you can easily use `saveRDS()` and `readRDS()` do achieve the same outcome.  It's not as future proof as the file dump out of `maxent` but it is very workable.

+ `AUC` and other model performance metrics and variable contribution ... these were readily available in the file output of `maxent`, but I'm still trying to noodle out how to harvest these from `maxnet`.

+ `variable response` is super easy to harvest out of `maxnet` compared to `maxent` (even though the latter is doable.)

I'm interested in learning more about the question you have raised.

**Comment by jamiemkass** [comment]
From what I understand, the implementation is very similar, but the outputs may vary slightly with maxent.jar. In particular, `maxnet` sometimes has trouble when too many hinge features are needed, but as this typically means the model is overfit, I don't think this capability is necessary for most cases. 

Additionally, Ben is right that features like calculating AUC and variable importance are not baked in, but these can be handled with other pkgs. For example, model tuning can be done with `ENMeval` or other pkgs to automate evaluation with cross-validation.

**Comment by rpatin** [comment]
Thank you for the information ! 
Concerning our package, we are mostly interested into differences in the model algorithm, as we have good support for calculating AUC and other metrics independently.
So what you say @jamiemkass is that models are highly similar, but are not based on the same algorithm, hence the lower support for hinge features in `maxnet` ? 
So when you limit hinge features you should obtain near-identical results between `maxnet` and `maxent` ?

**Comment by jamiemkass** [comment]
The technique is the same, but the base model is slightly different. And yes, without hinge features the models should be very similar. Even with them too, it's just that `glmnet`, the base pkg used in `maxnet`, can't handle too many hinge features. You'd need to ask @mrmaxent for any more details.

**Comment by mrmaxent** [comment]
Hi all, I don't have much to add here.  The models are conceptually the same, implemented very differently.  Maxent optimizes its model using custom java code.  Maxnet relies on glmnet to do the heavy lifting of the optimization.  Jamie is right that maxent can better handle lots of hinge features, because the code processes all hinges for a single feature together very efficiently, whereas maxnet's call to glmnet doesn't take advantage of the relationships between all those hinges.

**Comment by rpatin** [comment]
Hi @mrmaxent, @jamiemkass,
Thank you for your feedbacks, this is clearer for me now !
Best,
Rémi
