### ISSUE TITLE
When plot=FALSE, response.plot should return predictor values

### ISSUE THREAD

**Issue by johnbaums** [mrmaxent/maxnet#3]
Currently, when `plot=FALSE` is passed to `response.plot`, the returned object contains just the predictions. This would be more useful if the corresponding predictor values were also returned.

e.g. with

```r
else return(setNames(data.frame(m[, v], preds), c(v, 'pred')))
```

**Comment by mrmaxent** [comment]
Thanks, that's a useful addition.  I committed your suggested change.
