### ISSUE TITLE
remove warnings in response.plot with unlist

### ISSUE THREAD

**Issue by jamiemkass** [mrmaxent/maxnet#5]
If the line in response.plot:
`m <- data.frame(matrix(mm,nr,length(mm),byrow=T))`
is changed to:
`m <- data.frame(matrix(unlist(mm),nr,length(mm),byrow=T))`
the warnings (that I keep getting) are avoided.

**Comment by mrmaxent** [comment]
Thanks.  I made this change in maxnet.R instead, doing the unlist when the samplemeans are first created.
