### ISSUE TITLE
no open source license

### ISSUE THREAD

**Issue by rgommers** [mrmaxent/maxnet#6]
The README says "*This open source repository contains an R package ...*", however the license file only says:

    YEAR: 2016
    COPYRIGHT HOLDER: Steven Phillips

That's not an open source license, and as such this code cannot easily (legally) be built open. I assume the intention is for this to be open source? If so, can you please add a standard license?

**Comment by mrmaxent** [comment]
MIT license text has been added.

**Comment by rgommers** [comment]
thank you!
