### ISSUE TITLE
Possible issue with glmnet output format

### ISSUE THREAD

**Issue by andrefaa** [mrmaxent/maxnet#8]
Greetings,
While running maxnet sometimes I get the error "index larger than maximal"
I went inside the function and found out that this was happening in the step of L15 ( bb <- model$beta[,200]).
You had programmed to stop the function in L14 "if length(model$beta <200)". I don`t know if there was an update in glmnet, but the output of the glmnet model is an dgCMatrix, so it is possible that this is why the previous step is not stopping the function.
While I was able to solve this replacing length with ncol (although I don't know if this is correct), my question is if instead of column 200 can you set L15 to look for the last column of the model$beta matrix? I am not familiar with the glmnet output, so forgive me if this is a dumb question.

**Comment by robboyd** [comment]
I get this error too. Has anyone worked out how to fix it?

**Comment by mrmaxent** [comment]
We now check the length of model@lambda instead, so it should stop the function as intended.  Also, the reason that glmnet was sometimes not completing its regularization path was (as far as I know) that the fully-regularized model was infeasible.  We have solved this by making "addsamplestobackground" true by default in the current release.
